### ISSUE TITLE
Test compilation on windows failed

### ISSUE THREAD

**Issue by davidpfister** [FluidNumerics/feq-parse#20] opened 2024-01-24 22:55 UTC
I wanted to try out your equation parser. I used fpm as mentioned in the readme and downloaded the source code from your last release.
The command ```fpm test``` failed
![image](https://github.com/FluidNumerics/feq-parse/assets/23196745/2dd79ee6-642a-472f-950b-4725ee5566d8)

I am on Windows 10. I ran the command with elevated permissions (just in case). 
I tried with cmd and with msys. 
I also tried to compile with gfortran and ifort. 
In the end the result was always the same.

**Comment by fluidnumerics-joe** [comment] 2024-01-24 23:01
Thanks for reporting. I'll see if I can find an environment in which I can reproduce this issue. Without additional logs, I'll be stabbing in the dark here.

**Comment by fluidnumerics-joe** [comment] 2024-01-24 23:06
Looking through our GitHub actions, we only test under msys2 and gfortran. I'll look into adding msys and expanding windows testing. Currently we have a lot of paying customers in line for work at the moment, so I'm not sure when I'll get this resolved

**Comment by davidpfister** [comment] 2024-01-25 09:12
[build.log](https://github.com/FluidNumerics/feq-parse/files/14049335/build.log)
Here is the log I got when running ```fpm test --profile release --verbose``` > build.log

and fpm is up ta date
```
Version:     0.10.0, alpha
Program:     fpm(1)
Description: A Fortran package manager and build system
Home Page:   https://github.com/fortran-lang/fpm
License:     MIT
OS Type:     Windows
```

**Comment by fluidnumerics-joe** [comment] 2024-01-25 11:31
There are no errors in that build log. Am I missing something?

**Comment by fluidnumerics-joe** [comment] 2024-01-25 11:39
The only line that stands out is
```
Cannot open file 'build\gfortran_688A5DB7BAD2F9DA\test\test.exe.log': No such file or directory
```
But it doesn't seem to stop the build.

On another note, it doesn't appear that GitHub actions has a windows 10 environment out of the box.

**Comment by davidpfister** [comment] 2024-01-25 12:43
Right, I forgot to pipe the stderr. Using ```fpm test --profile release --verbose > build.log 2>&1``` also returns the error. But there is not much to see besides the problem you just reported and the line **The command line is too long.**. Attached is the new updated log.
[build.log](https://github.com/FluidNumerics/feq-parse/files/14052184/build.log)

**Comment by fluidnumerics-joe** [comment] 2024-01-25 14:08
Thanks. I'll add fpm with windows-latest with gfortran to the builds to see if I can reproduce the issue. Currently, our windows test uses CMake (which passes), so I suspect it might be worth trying to build with CMake for the moment.

**Comment by fluidnumerics-joe** [comment] 2024-01-25 14:50
Weird, it looks like this is the culprit

```
<ERROR> Unable to find build log " test.exe.log "
<ERROR> Compilation failed for object " test.exe "
Cannot open file 'build\gfortran_688A5DB7BAD2F9DA\test\test.exe.log': No such file or directory
```

This seems like an issue with fpm. We'll need to check issues on the fpm repository

**Comment by davidpfister** [comment] 2024-01-25 15:07
I did try with cmake but I got another issue: 
```
Missing variable is:
CMAKE_Fortran_PREPROCESS_SOURCE
```
my cmake detects automatically ifort by default and the options in the cmake file are given for unix kind of os (-fpp instead of /fpp, etc). I did not investiigate any further.
But this is another story for another time 😄 

I will also try to break you test cases into 2 or more folders to see if that reduces the command line length. I'll keep you posted

**Comment by fluidnumerics-joe** [comment] 2024-01-25 15:59
-fpp is a flag for the Intel compilers to enable preprocessing. You may be able to set `CMAKE_Fortran_PREPROCESS_SOURCE` to your ifort compiler with the `-fpp` flag during the CMake stage of the build. Though, my understanding is that CMake is supposed to detect and define this..

The fact that this is not found suggests that we ought to put a check in cmake to make sure it's set. 

This sounds like yet another mismatch between your specific environment and what we're testing for.

**Comment by davidpfister** [comment] 2024-01-25 21:13
@fluidnumerics-joe, I am not sure the options specified for cmake can work on Windows with ifort. If you look at the intel manual you will see that command lines on Windows are different (```/fpp``` instead of ```-fpp``` for instance). And it's the same for all options, some start with /Q... That makes it difficult to have something portable

**Comment by davidpfister** [comment] 2024-01-25 21:16
I splitted your test cases into 2 folders: ```trigo``` and ```intrinsic```. I added the following lines into the toml
```
[[test]]
name       = "test_intrinsic"
source-dir = "test/intrinsic"
main       = "test_intrinsic.f90"

[[test]]
name       = "test_trigo"
source-dir = "test/trigo"
main       = "test_trigo.f90"
```
And it works! 😄

**Comment by davidpfister** [comment] 2024-01-26 08:09
Hi @fluidnumerics-joe, the issue can be closed on my end. It seems that besides splitting your tests into multiple programs there is not much you can do. Thanks.

**Comment by fluidnumerics-joe** [comment] 2024-01-26 10:36
We've got a PR open to resolve this in the repository. I'm also going to add ifort on windows test to track down your CMake build issue.

It doesn't make sense that the tests need to be split. While it works, it's a band-aid for the underlying problem.

**Comment by fluidnumerics-joe** [comment] 2024-01-26 14:31
Pull request #21 resolves this issue.

What I found was that fpm was compiling all of the .f90 files under `test/` to .o files and the main test program was being built will all of the .o files linked. Since each unit test is brought in through an `include` statement, each unit test does not need to be compiled. The fix applied is to move the main `test.f90` for `fpm` to `test/fpm/test.f90` and update the `fpm.toml` to point to this main program.. Additionally, the `include` statements were updated to reference the unit tests in `test/`.

Thanks @davidpfister  for reporting the issue and experimenting - it helped in resolving this issue quickly!

For the moment, we are still not testing for Intel compilers on windows, but I suppose that will have to be an issue for another day. If you are interested, and able, you can add to the `.github/workflows/windows-ci.yml` the necessary steps to install intel fortran compilers, which would help this project out in supporting your desired platform.

**Closed by fluidnumerics-joe** 2024-01-26 14:31 UTC
